from pathlib import Path

from scripts import check_dependency_lock_contract as contract


def test_repository_dependency_lock_contract_is_closed() -> None:
    assert contract.dependency_lock_contract_problems() == []


def test_lock_gate_detects_requirement_without_hash(tmp_path: Path, monkeypatch) -> None:
    lock = tmp_path / "requirements.txt"
    lock.write_text(
        "# This file is autogenerated by pip-compile with Python 3.12\n"
        "example==1.0.0\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(contract, "ROOT", tmp_path)
    monkeypatch.setattr(contract, "LOCKS", {"requirements.txt": "Python 3.12"})

    problems = contract.lock_problems()

    assert any("requirement without hash" in problem for problem in problems)


def test_install_gate_detects_unhashed_requirements_command(tmp_path: Path, monkeypatch) -> None:
    workflows = tmp_path / "workflows"
    workflows.mkdir()
    (workflows / "bad.yml").write_text(
        "steps:\n  - run: python -m pip install -r requirements.txt\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(contract, "ROOT", tmp_path)
    monkeypatch.setattr(contract, "INSTALL_SURFACES", (workflows,))

    problems = contract.unhashed_install_problems()

    assert len(problems) == 1
    assert "--require-hashes" in problems[0]
