from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCKS = {
    "requirements.txt": "Python 3.12",
    "requirements-dev.txt": "Python 3.12",
    "requirements-py313.txt": "Python 3.13",
}
INSTALL_SURFACES = (
    ROOT / ".github" / "workflows",
    ROOT / "scripts" / "server_quality_gate.sh",
)
REQUIREMENT_START_RE = re.compile(r"^[a-zA-Z0-9_.-]+(?:\[[^]]+\])?==")


def lock_problems() -> list[str]:
    problems: list[str] = []
    for relative, python_marker in LOCKS.items():
        path = ROOT / relative
        if not path.is_file():
            problems.append(f"missing dependency lock: {relative}")
            continue
        text = path.read_text(encoding="utf-8")
        if "autogenerated by pip-compile" not in text:
            problems.append(f"not generated by pip-compile: {relative}")
        if not any(python_marker in line for line in text.splitlines()[:5]):
            problems.append(f"wrong Python lock marker: {relative} expected {python_marker}")
        if "--hash=sha256:" not in text:
            problems.append(f"lock has no hashes: {relative}")

        current_requirement = ""
        current_has_hash = False
        for raw_line in text.splitlines():
            line = raw_line.strip()
            if REQUIREMENT_START_RE.match(line):
                if current_requirement and not current_has_hash:
                    problems.append(f"requirement without hash in {relative}: {current_requirement}")
                current_requirement = line.split(" \\", 1)[0]
                current_has_hash = False
            elif current_requirement and line.startswith("--hash=sha256:"):
                current_has_hash = True
        if current_requirement and not current_has_hash:
            problems.append(f"requirement without hash in {relative}: {current_requirement}")
    return problems


def unhashed_install_problems() -> list[str]:
    problems: list[str] = []
    paths: list[Path] = []
    for surface in INSTALL_SURFACES:
        if surface.is_dir():
            paths.extend(sorted((*surface.glob("*.yml"), *surface.glob("*.yaml"))))
        elif surface.is_file():
            paths.append(surface)

    for path in paths:
        for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            line = raw_line.strip()
            if "pip install" not in line or "-r requirements" not in line:
                continue
            if "--require-hashes" not in line:
                problems.append(
                    f"{path.relative_to(ROOT)}:{line_number}: requirements install must use --require-hashes"
                )
    return problems


def dependency_lock_contract_problems() -> list[str]:
    return [*lock_problems(), *unhashed_install_problems()]


def main() -> int:
    problems = dependency_lock_contract_problems()
    if problems:
        print("DEPENDENCY_LOCK_CONTRACT_FAILED")
        for problem in problems:
            print(problem)
        return 1
    print("DEPENDENCY_LOCK_CONTRACT_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
